package parser;

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LOCAL_KWORD = 17;
  public static final int ASSIGN_OP = 3;
  public static final int TIMES_OP = 35;
  public static final int LESSEQUALS_OP = 39;
  public static final int LBRACKET = 22;
  public static final int BREAK_KWORD = 19;
  public static final int DO_KWORD = 4;
  public static final int EQUALS_OP = 43;
  public static final int RETURN_KWORD = 18;
  public static final int LPAREN = 29;
  public static final int MORE_OP = 42;
  public static final int REPEAT_KWORD = 7;
  public static final int NOT_KWORD = 47;
  public static final int END_KWORD = 5;
  public static final int RPAREN = 30;
  public static final int SEMICOLON = 2;
  public static final int THEN_KWORD = 10;
  public static final int SLASH_OP = 36;
  public static final int FUNCTION_KWORD = 16;
  public static final int DOT = 20;
  public static final int ELSEIF_KWORD = 11;
  public static final int IF_KWORD = 9;
  public static final int MINUS_UNOP = 49;
  public static final int EOF = 0;
  public static final int IN_KWORD = 15;
  public static final int RBRACKET = 23;
  public static final int LESS_OP = 41;
  public static final int POT_OP = 37;
  public static final int error = 1;
  public static final int AND_KWORD = 45;
  public static final int COMA = 14;
  public static final int NUMBER = 50;
  public static final int UNTIL_KWORD = 8;
  public static final int DIFFERENT_OP = 44;
  public static final int PLUS_OP = 33;
  public static final int MINUS_OP = 34;
  public static final int COLON = 21;
  public static final int PERCENT_OP = 38;
  public static final int FALSE_KWORD = 25;
  public static final int LBRACE = 31;
  public static final int NIL_KWORD = 24;
  public static final int WHILE = 6;
  public static final int MOREEQUALS_OP = 40;
  public static final int FOR_KWORD = 13;
  public static final int TRUE_KWORD = 26;
  public static final int RBRACE = 32;
  public static final int THREEDOTS = 27;
  public static final int STRING = 51;
  public static final int HASH_OP = 48;
  public static final int ELSE_KWORD = 12;
  public static final int TWODOTS = 28;
  public static final int OR_KWORD = 46;
  public static final int IDENTIFIER = 52;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "ASSIGN_OP",
  "DO_KWORD",
  "END_KWORD",
  "WHILE",
  "REPEAT_KWORD",
  "UNTIL_KWORD",
  "IF_KWORD",
  "THEN_KWORD",
  "ELSEIF_KWORD",
  "ELSE_KWORD",
  "FOR_KWORD",
  "COMA",
  "IN_KWORD",
  "FUNCTION_KWORD",
  "LOCAL_KWORD",
  "RETURN_KWORD",
  "BREAK_KWORD",
  "DOT",
  "COLON",
  "LBRACKET",
  "RBRACKET",
  "NIL_KWORD",
  "FALSE_KWORD",
  "TRUE_KWORD",
  "THREEDOTS",
  "TWODOTS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "PLUS_OP",
  "MINUS_OP",
  "TIMES_OP",
  "SLASH_OP",
  "POT_OP",
  "PERCENT_OP",
  "LESSEQUALS_OP",
  "MOREEQUALS_OP",
  "LESS_OP",
  "MORE_OP",
  "EQUALS_OP",
  "DIFFERENT_OP",
  "AND_KWORD",
  "OR_KWORD",
  "NOT_KWORD",
  "HASH_OP",
  "MINUS_UNOP",
  "NUMBER",
  "STRING",
  "IDENTIFIER"
  };
}

