
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ASSIGN_OP = 3;
  public static final int TIMES_OP = 21;
  public static final int LBRACKET = 15;
  public static final int LESSEQUALS_OP = 25;
  public static final int DO_KWORD = 4;
  public static final int EQUALS_OP = 29;
  public static final int LPAREN = 17;
  public static final int MORE_OP = 28;
  public static final int NOT_KWORD = 33;
  public static final int END_KWORD = 5;
  public static final int RPAREN = 18;
  public static final int SEMICOLON = 2;
  public static final int THEN_KWORD = 8;
  public static final int SLASH_OP = 22;
  public static final int DOT = 13;
  public static final int IF_KWORD = 7;
  public static final int MINUS_UNOP = 35;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int VAR_KWORD = 12;
  public static final int error = 1;
  public static final int POT_OP = 23;
  public static final int LESS_OP = 27;
  public static final int COMA = 10;
  public static final int AND_KWORD = 31;
  public static final int NUMBER = 36;
  public static final int DIFFERENT_OP = 30;
  public static final int PLUS_OP = 19;
  public static final int MINUS_OP = 20;
  public static final int COLON = 14;
  public static final int PERCENT_OP = 24;
  public static final int WHILE = 6;
  public static final int MOREEQUALS_OP = 26;
  public static final int FOR_KWORD = 11;
  public static final int STRING = 37;
  public static final int HASH_OP = 34;
  public static final int ELSE_KWORD = 9;
  public static final int OR_KWORD = 32;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "ASSIGN_OP",
  "DO_KWORD",
  "END_KWORD",
  "WHILE",
  "IF_KWORD",
  "THEN_KWORD",
  "ELSE_KWORD",
  "COMA",
  "FOR_KWORD",
  "VAR_KWORD",
  "DOT",
  "COLON",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "PLUS_OP",
  "MINUS_OP",
  "TIMES_OP",
  "SLASH_OP",
  "POT_OP",
  "PERCENT_OP",
  "LESSEQUALS_OP",
  "MOREEQUALS_OP",
  "LESS_OP",
  "MORE_OP",
  "EQUALS_OP",
  "DIFFERENT_OP",
  "AND_KWORD",
  "OR_KWORD",
  "NOT_KWORD",
  "HASH_OP",
  "MINUS_UNOP",
  "NUMBER",
  "STRING",
  "IDENTIFIER"
  };
}

