package main;
import java.io.FileNotFoundException;
import java.io.FileReader;


import java_cup.runtime.Symbol;
import lexer.Lexer;
import parser.parser;
import parser.sym;
import tree.Node;


public class Compiler {

   
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		//TODO: Alterar Path
		//String path = "/home/david/Documents/UFBA/8° semestre/Topicos em DB/workspace/compilua/src/exemplo.txt";
		String path = "C:/Users/Diego/Workspace/compilua.git/src/exemplo.txt";	
		
		Lexer scanner;
		try {
			scanner = new Lexer(new FileReader(path));
			/*//Print the tokens generated by the scanner
			Symbol s;
			do {
				s = scanner.debug_next_token();
			    System.out.println("token: "+s);
		    } while (s.sym != sym.EOF);*/
	        
			parser p = new parser(scanner);
			Symbol symbol = p.parse();
			Node root = (Node) symbol.value;
			
			root.print();
			
			
		} catch (FileNotFoundException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
	
	
}
